import { beforeEach, expect, test, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { http, HttpResponse } from 'msw';
import { AppProviders } from '../../app/AppProviders';
import { AppRoutes } from '../../app/routes/AppRoutes';
import { createSession } from '../../auth/services/session';
import { demoProfiles } from '../../auth/mocks/profiles';
import { server } from '../../common/testing/server';
import { createDemoHandlers } from '../../app/mocks/handlers';
import { locale, translations } from '../../i18n/pt-BR';
vi.mock('../../app/config', () => ({ demoMode: true }));
const text = translations[locale]; const copy = text.batch.manual;
beforeEach(() => { vi.spyOn(window, 'scrollTo').mockImplementation(() => undefined); server.use(...createDemoHandlers()); });
test('resultado incerto preserva rascunho ao consultar lotes e exige revisão explícita', async () => {
  let posts = 0;
  server.use(http.post('/api/batches', () => { posts++; return HttpResponse.error(); }));
  const session = createSession(); session.signIn(demoProfiles.operator);
  render(<MemoryRouter initialEntries={['/lotes/novo']}><AppProviders session={session}><AppRoutes /></AppProviders></MemoryRouter>);
  await userEvent.click(await screen.findByRole('button', { name: text.register.select }));
  await userEvent.type(screen.getByLabelText(text.batch.reference, { exact: false }), '00009');
  await userEvent.type(screen.getByLabelText(text.batch.faceValue, { exact: false }), '10,00');
  const date = screen.getByLabelText(text.batch.dueDate, { exact: false });
  await userEvent.type(date, '2099-12-31');
  await userEvent.click(screen.getByRole('button', { name: copy.addItem }));
  await userEvent.click(screen.getByRole('button', { name: copy.review }));
  await userEvent.click(screen.getByRole('button', { name: copy.confirm }));
  expect(await screen.findByRole('dialog')).toHaveTextContent(copy.uncertain);
  await userEvent.click(screen.getByRole('button', { name: text.common.understood }));
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  expect(screen.getByRole('button', { name: copy.resume })).toBeDisabled();
  await userEvent.click(screen.getByRole('link', { name: copy.consult }));
  await userEvent.click(await screen.findByRole('link', { name: text.batch.create.title }));
  expect(screen.getByRole('table', { name: copy.draftTable })).toHaveTextContent('00009');
  expect(screen.getByRole('button', { name: copy.resume })).toBeDisabled();
  await userEvent.click(screen.getByRole('checkbox', { name: copy.checked }));
  await userEvent.click(screen.getByRole('button', { name: copy.resume }));
  expect(screen.getByRole('button', { name: copy.review })).toBeEnabled();
  expect(posts).toBe(1);
});
