import { beforeEach, expect, test, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { http, HttpResponse } from 'msw';
import { AppProviders } from '../../app/AppProviders';
import { AppRoutes } from '../../app/routes/AppRoutes';
import { createSession } from '../../auth/services/session';
import { demoProfiles } from '../../../tests/auth/mocks/profiles';
import { server } from '../../../tests/common/testing/server';
import { createDemoHandlers } from '../../../tests/app/mocks/handlers';
import { assignorFixture } from '../../../tests/register/mocks/fixtures';
import { locale, translations } from '../../../tests/pt-BR';
const text = translations[locale]; const copy = text.batch.manual;
beforeEach(() => { vi.spyOn(window, 'scrollTo').mockImplementation(() => undefined); server.use(...createDemoHandlers()); });
test('resultado incerto preserva rascunho ao consultar lotes e exige revisão explícita', async () => {
  const user = userEvent.setup();
  let posts = 0;
  server.use(http.post('/api/batches', () => { posts++; return HttpResponse.error(); }));
  const session = createSession(); session.signIn(demoProfiles.operator, demoProfiles.operator.subject);
  render(<MemoryRouter initialEntries={['/lotes/novo']}><AppProviders session={session}><AppRoutes /></AppProviders></MemoryRouter>);
  await user.click(screen.getByRole('combobox', { name: copy.assignor }));
  await user.click(await screen.findByRole('option', { name: assignorFixture.name }));
  await user.type(screen.getByRole('textbox', { name: new RegExp(text.batch.reference) }), '00009');
  await user.type(screen.getByLabelText(text.batch.faceValue, { exact: false }), '10,00');
  const date = screen.getByLabelText(text.batch.dueDate, { exact: false });
  await user.type(date, '2099-12-31');
  await user.click(screen.getByRole('button', { name: copy.addItem }));
  await user.click(screen.getByRole('button', { name: copy.review }));
  await user.click(screen.getByRole('button', { name: copy.confirm }));
  expect(await screen.findByRole('dialog')).toHaveTextContent(copy.uncertain);
  await user.click(screen.getByRole('button', { name: text.common.understood }));
  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  expect(screen.getByRole('button', { name: copy.resume })).toBeDisabled();
  await user.click(screen.getByRole('link', { name: copy.consult }));
  await user.click(await screen.findByRole('link', { name: text.batch.create.title }));
  await user.click(screen.getByRole('button', { name: copy.viewReceivables }));
  const draft = await screen.findByRole('table', { name: copy.draftTable });
  expect(draft).toHaveTextContent('00009');
  await user.click(screen.getByRole('button', { name: text.common.close }));
  await waitFor(() => expect(screen.queryByRole('dialog', { name: copy.viewReceivables })).not.toBeInTheDocument());
  expect(screen.getByRole('button', { name: copy.resume })).toBeDisabled();
  await user.click(screen.getByRole('checkbox', { name: copy.checked }));
  await user.click(screen.getByRole('button', { name: copy.resume }));
  expect(screen.getByRole('button', { name: copy.review })).toBeEnabled();
  expect(posts).toBe(1);
}, 10000);
