import { test } from './isolatedTest';
import { expect } from '@playwright/test';
import { locale, translations } from '../tests/pt-BR';
const text = translations[locale]; const dash = text.dashboard; const statement = text.settlement.statement;
test('dashboard agrega uma vez por período e troca moeda sem consultas extras', async ({ page }, info) => {
  const requests: string[] = []; page.on('request', request => { if (request.url().includes('/api/')) requests.push(new URL(request.url()).pathname); });
  await page.goto('/dashboard'); await page.getByRole('button', { name: text.demo.manager, exact: true }).click();
  await expect(page.getByRole('group', { name: new RegExp(dash.chart) })).toBeVisible();
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden');
  expect(requests).toEqual(['/api/dashboard']);
  await expect(page.getByRole('link', { name: text.batch.create.title, exact: true })).toHaveCount(0);
  await page.getByRole('tab', { name: dash.currencies.USD, exact: true }).click();
  await expect(page.getByRole('table')).toHaveCount(0);
  const usdBar = page.locator('svg[role="group"] rect[role="img"][aria-label*="USD"]').first();
  await usdBar.hover();
  await expect(page.locator('svg text').filter({ hasText: 'USD' })).toBeVisible(); expect(requests).toHaveLength(1);
  await page.getByRole('combobox', { name: dash.period }).click(); await page.getByRole('option', { name: dash.periods.CURRENT_MONTH, exact: true }).click();
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden'); await expect.poll(() => requests).toEqual(['/api/dashboard', '/api/dashboard']);
  await expect(page.getByRole('tab', { name: dash.currencies.USD })).toHaveAttribute('aria-selected', 'true');
  await page.screenshot({ path: info.outputPath('dashboard.png'), fullPage: true });
  for (const width of [320, 390, 1366]) { await page.setViewportSize({ width, height: 768 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); }
});
test('extrato só aplica filtros sob ação; datas inválidas não consultam e atualização preserva edição', async ({ page }, info) => {
  const requests: string[] = []; page.on('request', req => { if (req.url().includes('/api/settlements/items')) requests.push(req.url()); });
  await page.goto('/extrato?from=2026-09-20&to=2026-09-27'); await page.getByRole('button', { name: text.demo.operator, exact: true }).click();
  await expect(page.getByRole('table', { name: statement.table })).toBeVisible(); await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden');
  expect(requests).toHaveLength(1); expect(new URL(requests[0]!).searchParams.get('start')).toBe('2026-09-20T03:00:00.000Z');
  await page.getByLabel(statement.from, { exact: true }).fill('2026-09-28'); await page.getByRole('button', { name: statement.apply, exact: true }).click();
  await expect(page.getByText(statement.rangeInvalid, { exact: true })).toBeVisible(); expect(requests).toHaveLength(1);
  await page.getByLabel(statement.from, { exact: true }).fill('2026-09-25');
  await page.getByRole('button', { name: statement.refresh, exact: true }).click();
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden'); await expect(page.getByLabel(statement.from, { exact: true })).toHaveValue('2026-09-25');
  await expect(page.getByRole('button', { name: statement.refresh, exact: true })).toBeFocused();
  expect(requests).toHaveLength(2); expect(new URL(requests[1]!).searchParams.get('start')).toBe('2026-09-20T03:00:00.000Z');
  await page.getByRole('button', { name: statement.apply, exact: true }).click(); await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden');
  await expect.poll(() => requests.length).toBe(3); expect(new URL(requests[2]!).searchParams.get('start')).toBe('2026-09-25T03:00:00.000Z');
  await page.getByRole('button', { name: statement.clear, exact: true }).click(); await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden');
  await expect.poll(() => requests.length).toBe(4);
  await expect(page.getByRole('button', { name: statement.clear, exact: true })).toBeFocused();
  expect(new URL(requests.at(-1)!).searchParams.has('start')).toBe(false); expect(new URL(requests.at(-1)!).searchParams.has('end')).toBe(false);
  await page.getByRole('combobox', { name: text.common.pagination.size }).click();
  await expect(page.getByRole('option')).toHaveText(['20', '50', '100']);
  await page.getByRole('option', { name: '100', exact: true }).click();
  await expect.poll(() => requests.length).toBe(5);
  expect(new URL(requests.at(-1)!).searchParams.get('size')).toBe('100');
  expect(new URL(requests.at(-1)!).searchParams.get('page')).toBe('1');
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden');
  await expect(page.getByRole('combobox', { name: text.common.pagination.size })).toBeFocused();
  await page.screenshot({ path: info.outputPath('statement.png'), fullPage: true });
  await page.setViewportSize({ width: 320, height: 768 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
